name: Rust

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Rustup
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      
    - name: Add arm7 toolchain
      run: rustup target add armv7-unknown-linux-gnueabihf
      
    - name: Add C compiler
      run: sudo apt-get install gcc-arm-linux-gnueabihf -y
      
    - name: Add C++ compiler
      run: sudo apt-get install g++-arm-linux-gnueabihf -y
    
    - name: Install FLTK Deps
      run: sudo apt-get install libx11-dev libxext-dev libxft-dev libxinerama-dev libxcursor-dev libxrender-dev libxfixes-dev libpango1.0-dev libgl1-mesa-dev libglu1-mesa-dev -y
      
    - name: Build
      run: cargo build --verbose --release --target=armv7-unknown-linux-gnueabihf
      
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: latest
        title: "Development ARM Build"
        files: target/armv7-unknown-linux-gnueabihf/release/fltk-test
